spring:
  application:
    name: eureka-server
  kubernetes:
    discovery:
      enabled: true

server:
  port: 8761

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://eureka-server.default.svc.cluster.local:8761/eureka
  instance:
    hostname: eureka-server.default.svc.cluster.local
    prefer-ip-address: false
