spring:
  application:
    name: gateway-server
  profiles:
    active: prod
  config:
    import: http://config-server.default.svc.cluster.local:8888
  cloud:
    loadbalancer:
      retry:
        enabled: true
    kubernetes:
      discovery:
        enabled: true
        all-namespaces: true