spring:
  application:
    name: gateway-server
  profiles:
    active: prod
  cloud:
    config:
      uri: http://config-server.default.svc.cluster.local:8888
    loadbalancer:
      retry:
        enabled: true
    kubernetes:
      discovery:
        enabled: true
        all-namespaces: true

