apiVersion: apps/v1
kind: Deployment
metadata:
  name: comment
  labels:
    app: comment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: comment
  template:
    metadata:
      labels:
        app: comment
    spec:
      containers:
        - name: comment
          image: cheonghalim/paranmanzang:comment
          ports:
            - containerPort: 8084

---
apiVersion: v1
kind: Service
metadata:
  name: comment
spec:
  selector:
    app: comment
  ports:
    - protocol: TCP
      port: 8084
      targetPort: 8084
  type: ClusterIP

