apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: config-server
  template:
    metadata:
      labels:
        app: config-server
    spec:
      containers:
        - name: config
          image: cheonghalim/paranmanzang:config
          ports:
            - containerPort: 8888
          env:
            - name: SPRING_CLOUD_KUBERNETES_ENABLED
              value: "true"
          volumeMounts:
            - mountPath: /home/paran/.ssh
              name: ssh-key-volume
              readOnly: true
      volumes:
        - name: ssh-key-volume
          secret:
            secretName: ssh-key
---
apiVersion: v1
kind: Service
metadata:
  name: config-server
spec:
  selector:
    app: config-server
  ports:
    - protocol: TCP
      port: 8888
  type: LoadBalancer
