apiVersion: apps/v1
kind: Deployment
metadata:
  name: file
  labels:
    app: file
spec:
  replicas: 1
  selector:
    matchLabels:
      app: file
  template:
    metadata:
      labels:
        app: file
    spec:
      containers:
        - name: file
          image: cheonghalim/paranmanzang:file
          ports:
            - containerPort: 8090
---
apiVersion: v1
kind: Service
metadata:
  name: file
spec:
  selector:
    app: file
  ports:
    - protocol: TCP
      port: 8090
      targetPort: 8090
  type: ClusterIP
