apiVersion: apps/v1
kind: Deployment
metadata:
  name: group
  labels:
    app: group
spec:
  replicas: 1
  selector:
    matchLabels:
      app: group
  template:
    metadata:
      labels:
        app: group
    spec:
      containers:
        - name: group
          image: cheonghalim/paranmanzang:group
          ports:
            - containerPort: 8085
          env:
            - name: EUREKA_SERVER_URL
              value: "http://eureka:8761/eureka"

---
apiVersion: v1
kind: Service
metadata:
  name: group
spec:
  selector:
    app: group
  ports:
    - protocol: TCP
      port: 8085
      targetPort: 8085
  type: ClusterIP
