apiVersion: apps/v1
kind: Deployment
metadata:
  name: room
  labels:
    app: room
spec:
  replicas: 1
  selector:
    matchLabels:
      app: room
  template:
    metadata:
      labels:
        app: room
    spec:
      containers:
        - name: room
          image: cheonghalim/paranmanzang:room
          ports:
            - containerPort: 8083
          env:
            - name: EUREKA_SERVER_URL
              value: "http://eureka:8761/eureka"

---
apiVersion: v1
kind: Service
metadata:
  name: room
spec:
  selector:
    app: room
  ports:
    - protocol: TCP
      port: 8083
      targetPort: 8083
  type: ClusterIP
