apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-server
  labels:
    app: gateway-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway-server
  template:
    metadata:
      labels:
        app: gateway-server
    spec:
      containers:
        - name: gateway
          image: cheonghalim/paranmanzang:gateway
          env:
          - name: SPRING_PROFILES_ACTIVE
            value: "prod"  # 활성화할 Spring 프로파일
          - name: SPRING_CLOUD_CONFIG_URI
            value: "http://default-config-server-982e4-100105172-e09c371f9669.kr.lb.naverncp.com:88"  # 외부 Config Server 도메인
          - name: EUREKA_CLIENT_REGISTER_WITH_EUREKA
            value: "true"
          - name: EUREKA_CLIENT_FETCH_REGISTRY
            value: "true"
          - name: EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE
            value: "http://default-eureka-server-6219b-100105199-770b06c1bd85.kr.lb.naverncp.com:87/eureka"  # 외부 Eureka 도메인
          ports:
            - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: gateway-server
spec:
  selector:
    app: gateway-server
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: LoadBalancer

